language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "14"
      env: SCRIPT=test
    - node_js: "12"
      env: SCRIPT=test
    - node_js: "10"
      env: SCRIPT=test
    - node_js: "12"
      env:
        - secure: IF01oyIKSs0C5dARdYRTilKnU1TG4zenjjEPClkQxAWIpUOxl9xcNJWDVEOPxJ/4pVt+pozyT80Rp7efh6ZiREJIQI1tUboBKSqZzSbnD5uViQNSbQ90PaDP0FIUc0IQ5o07W36rijBB0DTmtU1VofzN9PKkJO7XiSSXevI8RcM=
        - SAUCE_USERNAME=url-parse
        - SCRIPT=test-browser
script:
  - "npm run ${SCRIPT}"
after_script:
  - 'if [ "${SCRIPT}" == "test" ]; then c8 report --reporter=text-lcov | coveralls; fi'
notifications:
  irc:
    channels:
      - "irc.freenode.org#unshift"
    on_success: change
    on_failure: change
